SMART_SUGGESTIONS_APK="system/priv-app/SamsungSmartSuggestions/SamsungSmartSuggestions.apk"
SMART_SUGGESTIONS_RUNE="smali_classes15/com/samsung/android/smartsuggestions/featureconfig/rune/Rune.smali"
SMART_SUGGESTIONS_SSCO_REQUESTER="smali_classes15/com/samsung/android/smartsuggestions/search/core/embedding/i.smali"
SMART_SUGGESTIONS_SSCO_PROVIDER="smali_classes15/com/samsung/android/smartsuggestions/search/provider/ProviderCallMethod\$25.smali"
SMART_SUGGESTIONS_APK_DIR="$APKTOOL_DIR/system/${SMART_SUGGESTIONS_APK//system\/}"

ENABLE_SMART_SUGGESTIONS_RUNE()
{
    local METHOD="$1"

    SMALI_PATCH "system" "$SMART_SUGGESTIONS_APK" "$SMART_SUGGESTIONS_RUNE" "return" "$METHOD" "true" > /dev/null
}

DECODE_APK "system" "$SMART_SUGGESTIONS_APK" || return 1

LOG "- Repairing Smart Suggestions commonsense airport database"
if [ -s "$SMART_SUGGESTIONS_APK_DIR/assets/commonsense/airport_names_v1.0.0.csv.gzd" ] && \
        [ ! -s "$SMART_SUGGESTIONS_APK_DIR/assets/commonsense/airport_names_v1.0.1.csv.gzd" ]; then
    EVAL "cp -f \"$SMART_SUGGESTIONS_APK_DIR/assets/commonsense/airport_names_v1.0.0.csv.gzd\" \"$SMART_SUGGESTIONS_APK_DIR/assets/commonsense/airport_names_v1.0.1.csv.gzd\"" || return 1
fi

LOG "- Disabling unsupported Smart Suggestions SSCO semantic provider path"
SMALI_PATCH "system" "$SMART_SUGGESTIONS_APK" "$SMART_SUGGESTIONS_SSCO_REQUESTER" "replace" \
    "b(Ljava/lang/String;Ljava/lang/String;)[F" \
    "new-instance v0, Lcom/samsung/android/smartsuggestions/feature/aisuggestion/ui/test/c;" \
    "    const/4 p0, 0x0\n\n    return-object p0" \
    > /dev/null || true
SMALI_PATCH "system" "$SMART_SUGGESTIONS_APK" "$SMART_SUGGESTIONS_SSCO_REQUESTER" "return" \
    "d(Ljava/lang/String;)Z" \
    "false" \
    > /dev/null || true
SMALI_PATCH "system" "$SMART_SUGGESTIONS_APK" "$SMART_SUGGESTIONS_SSCO_REQUESTER" "return" \
    "e()Z" \
    "false" \
    > /dev/null || true
SMALI_PATCH "system" "$SMART_SUGGESTIONS_APK" "$SMART_SUGGESTIONS_SSCO_PROVIDER" "replace" \
    "invoke(Ljava/lang/String;Ljava/lang/String;Landroid/os/Bundle;)Landroid/os/Bundle;" \
    "invoke-virtual {p0, p3, p1}, Landroid/os/BaseBundle;->putBoolean(Ljava/lang/String;Z)V" \
    "invoke-virtual {p0, p3, v0}, Landroid/os/BaseBundle;->putBoolean(Ljava/lang/String;Z)V" \
    > /dev/null || true

LOG "- Silencing unsupported Smart Suggestions SSCO probes"
SMALI_PATCH "system" "$SMART_SUGGESTIONS_APK" "$SMART_SUGGESTIONS_SSCO_REQUESTER" "replace" \
    "c()J" \
    "invoke-static {v2, v1, v0}, Lcom/samsung/android/smartsuggestions/search/util/v;->k(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V" \
    "nop" \
    > /dev/null || true
SMALI_PATCH "system" "$SMART_SUGGESTIONS_APK" "$SMART_SUGGESTIONS_SSCO_PROVIDER" "replace" \
    "invoke(Ljava/lang/String;Ljava/lang/String;Landroid/os/Bundle;)Landroid/os/Bundle;" \
    "invoke-static {v1, p1, p2}, Lcom/samsung/android/smartsuggestions/search/util/v;->k(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)V" \
    "nop" \
    > /dev/null || true

LOG "- Enabling Smart Suggestions AI feature gates"
ENABLE_SMART_SUGGESTIONS_RUNE "getAI_VERSION_FEATURE_ENABLED()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getCOMMON_CONFIG_AI_VERSION_FOR_20263_GT_EQ()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getCOMMON_CONFIG_AI_VERSION_FOR_AI_OS_GT_EQ()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_ACTIVITY_FORECAST()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_AIRPORT_TTL()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_ANNIVERSARY_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_UI()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_NEW_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_BIRTHDAY_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_BIXBY_ACTION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_CAR_INFORMATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_COMMUTE_APP()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_CREATIVE_SELFIE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_CUSTOM_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_EDITABLE_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_EXERCISE_GREETING()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_GOOGLE_SPORTS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_HEALTH_NEW_DOCUMENT()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_APP_WIDGET()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SMART_SUGGESTION_APP_WIDGET()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_ONBOADING_PAGE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_INTEREST_SURVEY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_LISTEN_BRIEF()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_MESH_GRADIENT_BG_VI()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_MULTI_COLOR_GRADIENT_BG_VI()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_NANO_BANANA()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_PARKING_LOCATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_REFRESH_DOCUMENT_ON_STOP()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_SCROLL_TO_WIDGET()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_SLEEP_SCHEDULE_ALARM()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_SUN_VALLEY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_TRAVELING_POI_SUGGESTION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_TRAVELING_TRANSPORTATION_TO_ACCOMMODATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_TRAVELING_TRANSPORTATION_TO_AIRPORT()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_TRAVEL_PLAN_CONFIRMATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_TTL()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_UPCOMING_BIRTHDAY_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_VI()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_WIDGET_SETTINGS_DYNAMIC_WIDGET()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_WIDGET_SETTINGS_BACKGROUND()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_WIDGET_SETTINGS_BACKGROUND_SHAPE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_WIDGET_SETTINGS_DIM()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AI_SUGGESTION_WIDGET_SETTINGS_TRANSPARENCY()Z"

LOG "- Enabling Smart Suggestions Now/briefing gates"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_4x2_WIDGET_WEATHER_INFO()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AMBIENT_NUDGE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AUTOFILL_NUDGE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AUTO_ROTATE_WIDGETS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_BRIEF_LOCATION_AGREEMENT()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_BRIEF_SETTINGS_COMMAND_ACTION_HANDLER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_CALENDAR_HOLIDAY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_IN_APP_NUDGE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOTIFICATION_NUDGE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOW_NUDGE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOW_NUDGE_HIDE_RECALL_DATE_WHEN_TODAY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOW_NUDGE_RECALL_PDE_BUSINESS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOW_NUDGE_SAVE_PLACES_ACTION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NUDGE_EXPAND()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOW_BRIEF_FOR_AI_OS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOW_BRIEF_ON_LOCK_AND_HOME()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NOW_BRIEF_BUDS_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_BRIEF_MESSAGE_LLM()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_BRIEF_MESSAGE_LLM_BG()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_BRIEF_WEATHER_LLM()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AUDIO_BRIEF_MESSAGE_LLM()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AUDIO_BRIEF_FF_REW()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_AUDIO_BRIEF_SPEED_CONTROL()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SNAP_SYNC_NUDGE()Z"

LOG "- Enabling Smart Suggestions on-device intelligence gates"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_PERSONAL_DATA_ENGINE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_DEVICE_AI_LLM_VERSION_V3()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_LLM()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_ON_DEVICE_3B_MODEL()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_CONTENTS_AI_ASSISTANTS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SMART_MEMORY_MANAGER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_EMAIL_COLLECTOR()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_CCS_COLLECTOR()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SCREENSHOT_COLLECTOR()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_MEDIA_SEARCH_FOR_TAGGING()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_FAMILIARITY_INFERENCE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_CLICKSTREAM()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_FORWARDING_CHAT_CONVERSATION_TO_DATA_PLATFORM()Z"

LOG "- Enabling Smart Suggestions generated reply and assistant gates"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_CALL_TRANSCRIPT_SUGGESTION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_CHAT_TRANSLATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SMART_REPLY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SMART_REPLY_CATEGORY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SMART_REPLY_RESOLVE_DEPENDENT_APP_UPDATE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_FTU_DISCOVER_NUDGE_FOR_KEYBOARD_ONLY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SAMSUNG_PASS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SOCIAL_COMPOSER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SUGGESTED_REPLIES_V1()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SUGGESTED_REPLIES_V2()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SUGGESTED_REPLIES_V3()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SUGGESTED_REPLIES_MESSAGE_RECEIVER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SUGGESTED_REPLIES_GEN_UI_NUDGE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SUGGESTED_REPLIES_LLM_PREWARM()Z"

LOG "- Enabling Smart Suggestions card provider gates"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_BIXBY_TRANSPORTATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_DOMESTIC_TRAVEL()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_EMERGENCY_ALERTS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_GEN_WEATHER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_WEATHER_20263()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_WEATHER_APP_DOMAIN()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_GEMINI_FORTUNE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_GEMINI_STOCK()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_GEMINI_TRANSPORTATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_GEMINI_TRAVEL()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_GEMINI_TRAVEL_GET_RICHER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_PERPLEXITY()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_STELLA()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_LIFE_INDICES_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_MESSAGE_DOCUMENT_CMAS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_MONEY_TRANSFER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NETFLIX_NEW_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_NEWS_NEW_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_PAY_NOW_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_READY_TO_CELEBRATE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_RECURRING_PAYMENTS()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SA_TRAVEL_RECOMMEND()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SEND_MONEY_AMOUNT()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SECURE_INSIGHT()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SECURITY_BRIEF()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SKETCHBOOK_DRAWING()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SKETCHBOOK_DRAWING_POPOVER()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_PRIORITY_NOTIFICATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_SUMMARY_NOTIFICATION()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_S_ROAMING_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_TODAY_IN_HISTORY_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_WARRANTY_AND_CARE()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_WEEKEND_RECOMMEND_CARD()Z"
ENABLE_SMART_SUGGESTIONS_RUNE "getSUPPORT_YOUTUBE_NEW_CARD()Z"

unset -f ENABLE_SMART_SUGGESTIONS_RUNE
unset SMART_SUGGESTIONS_APK SMART_SUGGESTIONS_RUNE SMART_SUGGESTIONS_SSCO_REQUESTER SMART_SUGGESTIONS_SSCO_PROVIDER SMART_SUGGESTIONS_APK_DIR
