SET_PROP_IF_DIFF "vendor" "ro.security.fips.ux" "Disabled"

_DELETE_FROM_WORK_DIR_IF_EXISTS()
{
    local PARTITION="$1"
    local FILE="$2"
    local FILE_PATH="$WORK_DIR/$PARTITION/$FILE"

    if [ -e "$FILE_PATH" ] || [ -L "$FILE_PATH" ]; then
        DELETE_FROM_WORK_DIR "$PARTITION" "$FILE"
    fi
}

# KnoxGuard
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxGuard"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.kgclient.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/signature-permissions-com.samsung.android.kgclient.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.kg30-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.kg-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.kg30-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.kg-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.tlc.kg-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.kg30-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.kg30-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.kg-V1-ndk_platform.so"

# DualDAR
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/bin/dualdard"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/init/dualdard.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libdualdar.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/aidl_comm_ddar_client.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.tlc.ddar-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.ddar-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.ddar@1.0-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.ddar-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.ddar@1.0-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.tlc.ddar-default.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.tlc.ddar@1.0-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libtlc_comm_ddar_aidl.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libtlc_comm_ddar.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libtlc_direct_comm_ddar_aidl.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libtlc_direct_comm_ddar.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.ddar-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.ddar@1.0-impl.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.ddar@1.0.so"

# Blockchain
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/app/BlockchainBasicKit"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/service-samsung-blockchain.jar"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/service-samsung-blockchain.jar.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-blockchain.odex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-blockchain.odex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-blockchain.vdex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-blockchain.vdex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/sysconfig/preinstalled-packages-com.samsung.android.coldwalletservice.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libtlc_blockchain_comm.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libtlc_blockchain_keystore.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libtlc_blockchain_direct_comm.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/blockchain_aidl_comm_client.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.tlc.blockchain-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.blockchain-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.blockchain@1.0-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.blockchain-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.blockchain@1.0-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.tlc.blockchain-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.blockchain-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.blockchain@1.0-impl.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.blockchain@1.0.so"
SET_FLOATING_FEATURE_CONFIG "SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_BLOCKCHAIN_SERVICE" --delete

# Samsung Payment / MPOS
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/service-samsung-payment.jar"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/service-samsung-payment.jar.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-payment.odex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-payment.odex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-payment.vdex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/service-samsung-payment.vdex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/PaymentFramework"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.mpos.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libtlc_payment_direct_comm.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libtlc_payment_spay.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libtlc_payment_comm.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/payment_aidl_comm_client.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libhidl_comm_mpos_tui_client.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.mpos-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.tlc.mpos_tui@1.0.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.tlc.payment-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxMposAgent"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.mpos-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.mpos_tui@1.0-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.payment-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.tlc.payment@1.0-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/mpos-default-sec.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.mpos_tui@1.0-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.payment-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.tlc.payment@1.0-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/mpos-default-sec.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.tlc.mpos_tui@1.0-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.tlc.payment-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libtlc_comm_mpos_tui.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libtlc_direct_comm_mpos_tui.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.mpos-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.mpos_tui@1.0-impl.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.mpos_tui@1.0.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.payment-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.payment@1.0-impl.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.tlc.payment@1.0.so"

# eSE / SEM
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/bin/sem_daemon"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/init/sem_early.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.sem.factoryapp.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libsec_sem.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libsec_semAidl.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libsec_semRil.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libsec_semTlc.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.security.sem-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/SEMFactoryApp"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.security.sem-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.security.sem@1.0-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.security.sem-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.security.sem@1.0-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.security.sem-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib/libsec_semRil.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libsec_semHalTlc.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libsec_semRil.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libril_sem.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.security.sem-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.security.sem@1.0.so"

# HDM
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/HdmApk"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.hdmapp.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.tlc.hdm@1.0.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.tlc.hdm@1.1.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.tlc.hdm@1.2.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hdm_status.sh"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.khdm-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/khdm-default-sec.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/khdm-default-sec.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.khdm-V2-ndk.so"

# WSM
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/public.libraries-wsm.samsung.txt"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libhal.wsm.samsung.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.security.wsm.service-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hw/vendor.samsung.hardware.security.wsm-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/vendor.samsung.hardware.security.wsm@1.0-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/wsm-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.security.wsm.service-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libhal.wsm.samsung.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libwsmd_functions.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.security.wsm.service-V1-ndk.so"

# Knox ZeroTrust
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/bin/ztd"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/bin/bpfloader_kzt"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/init/ztd.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/init/bpfloader_kzt.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/ztsdk.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.zt.framework.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/ztsdk.jar"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/ztsdk.jar.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/ztsdk.odex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/ztsdk.odex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/ztsdk.vdex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/ztsdk.vdex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libztnativesdk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libzt_binder.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxZtFramework"
for f in ztdScIoctl.o ztdScClose.o ztdScMount.o ztdScOpen.o ztdScChmod.o ztdPrivEscal.o ztdMdd.o ztdPkt.o ztdScMemfdCreate.o ztdScExecve.o ztdScChown.o ztdFs.o ztdProc.o ztdSk.o; do
    _DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/bpf/$f"
done
unset f

# Knox Matrix
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/bin/fabric_crypto"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/init/fabric_crypto.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/FabricCryptoLib.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.kmxservice.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/vintf/manifest/fabric_crypto_manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/FabricCryptoLib.jar"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/FabricCryptoLib.jar.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/FabricCryptoLib.odex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/FabricCryptoLib.odex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/FabricCryptoLib.vdex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/FabricCryptoLib.vdex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/com.samsung.security.fabric.cryptod-V1-cpp.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.security.fkeymaster-V1-cpp.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.security.fkeymaster-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KmxService"

# Knox Analytics / MTD
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/knoxanalytics.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/knoxanalyticssdk.jar"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/knoxanalyticssdk.jar.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/knox_mtd.jar"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/knox_mtd.jar.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knoxanalyticssdk.odex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knoxanalyticssdk.odex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knoxanalyticssdk.vdex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knoxanalyticssdk.vdex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knox_mtd.odex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knox_mtd.odex.fsv_meta"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knox_mtd.vdex"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/framework/oat/arm64/knox_mtd.vdex.fsv_meta"

# VaultKeeper / Hermes
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libhermes_cred.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libhermes_jni.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.security.hermes-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/vendor.samsung.hardware.security.vaultkeeper-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/hermesd"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/vaultkeeperd"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/vendor.samsung.hardware.security.vaultkeeper-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "bin/vendor.samsung.hardware.security.vaultkeeper@2.0-service"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/hermesd.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vaultkeeper_common.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/init/vendor.samsung.hardware.security.vaultkeeper-service.rc"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.security.hermes.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vendor.samsung.hardware.security.vaultkeeper-manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "etc/vintf/manifest/vaultkeeper_manifest.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib/libhermes.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libhermes.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libhermes_bdbridge.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libhermes_cred.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/libhwvault.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.security.hermes-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.security.vaultkeeper-V1-ndk.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "vendor" "lib64/vendor.samsung.hardware.security.vaultkeeper@2.0.so"

# Other Knox APKs and framework declarations
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/public.libraries-knox.samsung.txt"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/knox_sdk_api_level_40.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/knoxsdk_edm.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/knoxsdk_mdm.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.knox.vpn.proxyhandler.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.analytics.uploader.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.app.networkfilter.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.attestation.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.containercore.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.er.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.kfbp.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.knnr.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.kpecore.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.pushmanager.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.sandbox.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/privapp-permissions-com.samsung.knox.securefolder.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/permissions/signature-permissions-com.sec.enterprise.knox.cloudmdm.smdms.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/etc/default-permissions/default-permissions-com.sec.enterprise.knox.cloudmdm.smdms.xml"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libjni_knoxnwfilterparser.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libknox_filemanager.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libknox_remotedesktopclient.knox.samsung.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/lib64/libknoxnative_shared.so"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KPECore"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxCore"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxERAgent"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxFrameBufferProvider"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxNetworkFilter"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxNeuralNetworkRuntime"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxPushManager"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/KnoxSandbox"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/knoxanalyticsagent"
_DELETE_FROM_WORK_DIR_IF_EXISTS "system" "system/priv-app/knoxvpnproxyhandler"

unset -f _DELETE_FROM_WORK_DIR_IF_EXISTS
